# Generated by Django 5.2.4 on 2025-08-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_alter_ticket_reservation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "show_session")},
        ),
    ]
