# Generated by Django 5.2.4 on 2025-08-03 09:36

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0005_alter_ticket_options_alter_showtheme_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetariumdome",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium.models.planetarium_dome_image_path,
            ),
        ),
    ]
